### ISSUE TITLE
results_nn = a.play(n)// error... Index exceeds matrix dimensions.

### ISSUE THREAD

**Issue by aysegulucar2016** [tambetm/matlab2048#4]
How can I solve the problem. I run example.m. results_nn = a.play(n) provides an error.
opts.minibatch_size = 100;
a = NNAgent(opts);
% Plays n games
results_nn = a.play(n)
Index exceeds matrix dimensions.

Error in nnff (line 38)
        nn.a{i} = [ones(m,1) nn.a{i}];

Error in NNAgent/predict (line 186)
            this.nnet = nnff(this.nnet, x, zeros(size(x,1), this.nnet.size(end)));

Error in NNAgent/play (line 97)
                        qvalues = this.predict(this.game.state);

**Comment by tambetm** [comment]
Sorry, I'm not able to support this project any more. There are number of implementations around that work much better, see https://www.google.ee/search?client=ubuntu&channel=fs&q=2048+deep+learning&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=D-wKWY-OFeuO8Qe2yZfoDA.

**Comment by aalanwar** [comment]
change the activation function in line 20 in the example.m to a supported activation function 
`opts.activation_function = 'sigm'; % or 'tanh_opt' instead of  'relu';`

@tambetm 
Thanks for writing this code!

**Comment by tambetm** [comment]
I used my own fork of DeepLearnToolbox, which includes relu support: https://github.com/tambetm/DeepLearnToolbox.
